<?php
/**
 * Printable Site Health report.
 *
 * A standalone document. No admin stylesheet, no admin script, no plugin
 * images, no web fonts — the page has to render identically when it is opened
 * from a link, saved to disk, or handed to the browser's print engine, and
 * anything it loads from somewhere else is one more thing that can be missing
 * at that moment.
 *
 * Expects:
 *   $my_site_hand_view       array  Built by Report_Exporter::build_view().
 *   $my_site_hand_auto_print bool   Open the print dialog on load.
 *
 * @package MySiteHand
 */

defined( 'ABSPATH' ) || exit;

// phpcs:disable Generic.Commenting.DocComment.MissingShort -- Type hints for the caller's locals, not documented blocks.
/** @var array<string, mixed> $my_site_hand_view Everything this page renders. */
/** @var bool $my_site_hand_auto_print Whether to open the print dialog on load. */
// phpcs:enable Generic.Commenting.DocComment.MissingShort

$my_site_hand_footer_text = __( 'Generated by My Site Hand', 'my-site-hand' );

?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex, nofollow">
	<title><?php
		printf(
			/* translators: %s: site name */
			esc_html__( 'Site Health Report — %s', 'my-site-hand' ),
			esc_html( $my_site_hand_view['site_name'] )
		);
	?></title>
	<style>
		:root {
			--msh-ink: #1c1c1c;
			--msh-muted: #5a5a5a;
			--msh-rule: #d8d8d8;
			--msh-good: #17734a;
			--msh-warning: #8a5a00;
			--msh-critical: #a11b1b;
		}

		* { box-sizing: border-box; }

		body {
			margin: 0;
			padding: 32px 28px 96px;
			background: #fff;
			color: var(--msh-ink);
			font: 13px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
			-webkit-print-color-adjust: exact;
			print-color-adjust: exact;
		}

		.msh-doc { max-width: 860px; margin: 0 auto; }

		.msh-head {
			display: flex;
			justify-content: space-between;
			align-items: flex-start;
			gap: 24px;
			padding-bottom: 18px;
			border-bottom: 2px solid var(--msh-ink);
		}

		.msh-site-name { margin: 0 0 4px; font-size: 21px; line-height: 1.25; }
		.msh-site-url { margin: 0; font-size: 12px; color: var(--msh-muted); word-break: break-all; }
		.msh-scanned { margin: 8px 0 0; font-size: 12px; color: var(--msh-muted); }

		.msh-score { text-align: right; flex: 0 0 auto; }
		.msh-score-num { display: block; font-size: 46px; line-height: 1; font-weight: 700; }
		.msh-score-of { font-size: 14px; font-weight: 400; color: var(--msh-muted); }
		.msh-score-band { display: block; margin-top: 4px; font-size: 13px; font-weight: 600; }
		.msh-score-delta { display: block; margin-top: 2px; font-size: 12px; color: var(--msh-muted); }

		.msh-band-good { color: var(--msh-good); }
		.msh-band-warning { color: var(--msh-warning); }
		.msh-band-critical { color: var(--msh-critical); }

		.msh-summary { width: 100%; border-collapse: collapse; margin: 22px 0 8px; }
		.msh-summary th,
		.msh-summary td { text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--msh-rule); font-size: 12px; }
		.msh-summary th { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: var(--msh-muted); }
		.msh-summary td:last-child,
		.msh-summary th:last-child { text-align: right; }

		.msh-check {
			margin-top: 22px;
			padding-top: 14px;
			border-top: 1px solid var(--msh-rule);
			page-break-inside: avoid;
			break-inside: avoid;
		}

		.msh-check-head {
			display: flex;
			justify-content: space-between;
			align-items: baseline;
			gap: 16px;
		}

		.msh-check-name { margin: 0; font-size: 15px; }
		.msh-check-status { font-size: 12px; color: var(--msh-muted); white-space: nowrap; }

		.msh-issues { margin: 10px 0 0; padding: 0; list-style: none; }

		.msh-issue {
			padding: 6px 0 6px 74px;
			position: relative;
			border-bottom: 1px dotted var(--msh-rule);
			page-break-inside: avoid;
			break-inside: avoid;
		}

		.msh-issue:last-child { border-bottom: 0; }

		.msh-sev {
			position: absolute;
			left: 0;
			top: 7px;
			font-size: 10px;
			text-transform: uppercase;
			letter-spacing: .05em;
			font-weight: 700;
		}

		.msh-issue-title { display: block; word-break: break-word; }
		.msh-issue-context { display: block; font-size: 12px; color: var(--msh-muted); word-break: break-word; }

		.msh-more { margin: 8px 0 0; font-size: 12px; color: var(--msh-muted); font-style: italic; }
		.msh-none { margin: 8px 0 0; font-size: 12px; color: var(--msh-muted); }

		.msh-toolbar {
			max-width: 860px;
			margin: 0 auto 22px;
			display: flex;
			gap: 10px;
			align-items: center;
		}

		.msh-print-btn {
			font: inherit;
			padding: 7px 14px;
			border: 1px solid var(--msh-ink);
			background: var(--msh-ink);
			color: #fff;
			cursor: pointer;
		}

		.msh-toolbar-note { font-size: 12px; color: var(--msh-muted); }

		.msh-foot {
			margin-top: 30px;
			padding-top: 12px;
			border-top: 1px solid var(--msh-rule);
			font-size: 11px;
			color: var(--msh-muted);
		}

		.msh-foot a { color: inherit; }

		.msh-print-foot { display: none; }

		/* The whole document sits in one table so its <tfoot> can repeat on
		   every printed page. On screen it behaves like a plain block. */
		.msh-sheet {
			width: 100%;
			max-width: 860px;
			margin: 0 auto;
			border-collapse: collapse;
		}

		.msh-sheet > tbody > tr > td,
		.msh-sheet > tfoot > tr > td {
			padding: 0;
			vertical-align: top;
		}

		.msh-sheet > tfoot { display: table-footer-group; }

		@media print {
			@page {
				margin: 14mm 12mm 18mm;
			}

			body { padding: 0; font-size: 11px; }

			/* Anything that only makes sense on a screen. */
			.msh-toolbar,
			.msh-foot { display: none !important; }

			.msh-check { page-break-inside: avoid; break-inside: avoid; }

			/* Keep a heading with the rows it introduces rather than stranding
			   it at the bottom of a page. */
			.msh-check-head { page-break-after: avoid; break-after: avoid; }

			.msh-summary { page-break-inside: avoid; break-inside: avoid; }

			a[href]::after { content: ""; }

			/* Repeats on every sheet: this report is meant to be sent to
			   someone, and it should say where it came from wherever they
			   open it.

			   It lives in a <tfoot> rather than a fixed-position element on
			   purpose. `position: fixed` is out of flow, so it repeats on
			   every page but reserves no room, and the last line of a full
			   page prints straight through it. A repeating table footer both
			   repeats AND takes up space, which is the whole point. */
			.msh-print-foot {
				display: block;
				padding-top: 4px;
				border-top: 1px solid var(--msh-rule);
				font-size: 9px;
				color: var(--msh-muted);
			}
		}
	</style>
</head>
<body>

	<div class="msh-toolbar">
		<button type="button" class="msh-print-btn" id="msh-print"><?php esc_html_e( 'Print or save as PDF', 'my-site-hand' ); ?></button>
		<span class="msh-toolbar-note"><?php esc_html_e( 'Choose "Save as PDF" as the destination in your browser\'s print dialog.', 'my-site-hand' ); ?></span>
	</div>

	<table class="msh-sheet">
		<tfoot>
		<tr>
			<td>
				<div class="msh-print-foot">
					<?php echo esc_html( $my_site_hand_footer_text ); ?> — <?php echo esc_html( $my_site_hand_view['plugin_url'] ); ?>
				</div>
			</td>
		</tr>
		</tfoot>
		<tbody>
		<tr>
			<td>
	<div class="msh-doc">

		<header class="msh-head">
			<div>
				<h1 class="msh-site-name"><?php echo esc_html( $my_site_hand_view['site_name'] ); ?></h1>
				<p class="msh-site-url"><?php echo esc_html( $my_site_hand_view['site_url'] ); ?></p>
				<p class="msh-scanned"><?php
					printf(
						/* translators: %s: date and time the scan ran */
						esc_html__( 'Scanned %s', 'my-site-hand' ),
						esc_html(
							wp_date(
								get_option( 'date_format' ) . ' ' . get_option( 'time_format' ),
								$my_site_hand_view['generated']
							)
						)
					);
				?></p>
			</div>

			<div class="msh-score">
				<span class="msh-score-num"><?php echo esc_html( (string) $my_site_hand_view['score'] ); ?><span class="msh-score-of"><?php esc_html_e( '/100', 'my-site-hand' ); ?></span></span>
				<span class="msh-score-band msh-band-<?php echo esc_attr( $my_site_hand_view['band'] ); ?>"><?php echo esc_html( $my_site_hand_view['band_label'] ); ?></span>
				<?php if ( null !== $my_site_hand_view['delta'] ) : ?>
					<span class="msh-score-delta"><?php
						printf(
							/* translators: 1: signed score change such as "+6", 2: the previous score */
							esc_html__( '%1$s since the last scan (was %2$d)', 'my-site-hand' ),
							esc_html( ( $my_site_hand_view['delta'] >= 0 ? '+' : '' ) . $my_site_hand_view['delta'] ),
							(int) $my_site_hand_view['previous']
						);
					?></span>
				<?php endif; ?>
			</div>
		</header>

		<table class="msh-summary">
			<thead>
				<tr>
					<th scope="col"><?php esc_html_e( 'Check', 'my-site-hand' ); ?></th>
					<th scope="col"><?php esc_html_e( 'Result', 'my-site-hand' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $my_site_hand_view['checks'] as $my_site_hand_check ) : ?>
					<tr>
						<td><?php echo esc_html( $my_site_hand_check['label'] ); ?></td>
						<td><?php echo esc_html( $my_site_hand_check['status_text'] ); ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>

		<?php foreach ( $my_site_hand_view['checks'] as $my_site_hand_check ) : ?>
			<section class="msh-check">
				<div class="msh-check-head">
					<h2 class="msh-check-name"><?php echo esc_html( $my_site_hand_check['label'] ); ?></h2>
					<span class="msh-check-status"><?php echo esc_html( $my_site_hand_check['status_text'] ); ?></span>
				</div>

				<?php if ( ! empty( $my_site_hand_check['issues'] ) ) : ?>
					<ul class="msh-issues">
						<?php foreach ( $my_site_hand_check['issues'] as $my_site_hand_issue ) : ?>
							<li class="msh-issue">
								<span class="msh-sev msh-band-<?php echo esc_attr( 'critical' === $my_site_hand_issue['severity'] ? 'critical' : ( 'warning' === $my_site_hand_issue['severity'] ? 'warning' : 'good' ) ); ?>">
									<?php echo esc_html( $my_site_hand_issue['severity'] ); ?>
								</span>
								<span class="msh-issue-title"><?php echo esc_html( (string) $my_site_hand_issue['title'] ); ?></span>
								<?php if ( ! empty( $my_site_hand_issue['context'] ) ) : ?>
									<span class="msh-issue-context"><?php echo esc_html( (string) $my_site_hand_issue['context'] ); ?></span>
								<?php endif; ?>
							</li>
						<?php endforeach; ?>
					</ul>

					<?php if ( $my_site_hand_check['remaining'] > 0 ) : ?>
						<p class="msh-more"><?php
							printf(
								esc_html(
									/* translators: %d: number of issues found but not listed in this report */
									_n(
										'%d more issue was found but is not listed here.',
										'%d more issues were found but are not listed here.',
										$my_site_hand_check['remaining'],
										'my-site-hand'
									)
								),
								(int) $my_site_hand_check['remaining']
							);
						?></p>
					<?php endif; ?>
				<?php else : ?>
					<p class="msh-none"><?php echo esc_html( $my_site_hand_check['status_text'] ); ?></p>
				<?php endif; ?>
			</section>
		<?php endforeach; ?>

		<p class="msh-foot">
			<?php echo esc_html( $my_site_hand_footer_text ); ?> —
			<a href="<?php echo esc_url( $my_site_hand_view['plugin_url'] ); ?>"><?php echo esc_html( $my_site_hand_view['plugin_url'] ); ?></a>
		</p>
	</div>
			</td>
		</tr>
		</tbody>
	</table>

	<script>
		(function () {
			var button = document.getElementById('msh-print');

			if (button) {
				button.addEventListener('click', function () {
					window.print();
				});
			}

			<?php if ( $my_site_hand_auto_print ) : ?>
			// Wait for layout before opening the dialog, or the preview can be
			// generated from a half-laid-out page.
			window.addEventListener('load', function () {
				window.setTimeout(function () {
					window.print();
				}, 250);
			});
			<?php endif; ?>
		}());
	</script>

</body>
</html>
